# Generated by Django 3.1.2 on 2022-06-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='comment1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='module',
            name='comment2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='module',
            name='comment3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='module',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
