# Generated by Django 3.1.2 on 2022-06-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderate', '0005_auto_20220611_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='emotions',
            field=models.CharField(default='1.0,1.0,1.0,1.0,1.0', max_length=200),
        ),
    ]
